### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by micagroup** [isleensolutions/vtigerTemplate#1]
Hi guys,

I am a bit confused about which files go where?
Could you give us a simple instruction set?

Kind regards,

Mike

**Comment by mustafhae** [comment]
Hi Mike

The template is tested for vtiger 6. to install 
You need to copy isleenlayout folder to layout folder and isleen folder to libraries. change the default theme in viewer class.

**Comment by micagroup** [comment]
Thanks for the quick reply!
I will check it out

**Comment by micagroup** [comment]
Hi,

Should it be changed like this;
    const DEFAULTLAYOUT = 'vlayout';
    const DEFAULTTHEME  = 'isleen';

?

**Comment by mustafhae** [comment]
const DEFAULTLAYOUT = 'isleenlayout';

**Comment by micagroup** [comment]
I am getting a l lot of errors. I did follow your instructions to the letter.
info.png / settings.png are missing. Errors with AccessDenied, when going to Administrator > CRM Settings I get: Unable to load template file 'modules/Vtiger/uitypes/PhoneDetailView.tpl' in 'modules/Vtiger/DetailViewBlockView.tpl

I now have:
const DEFAULTLAYOUT = 'isleenlayout';
const DEFAULTTHEME = 'isleen';

**Comment by mustafhae** [comment]
Disable notification functionality
On 23 Jul 2015 20:20, micagroup notifications@github.com wrote:I am getting a l lot of errors. I did follow your instructions to the letter.
info.png / settings.png are missing. Errors with AccessDenied, when going to Administrator > CRM Settings I get: Unable to load template file 'modules/Vtiger/uitypes/PhoneDetailView.tpl' in 'modules/Vtiger/DetailViewBlockView.tpl

I now have:
const DEFAULTLAYOUT = 'isleenlayout';
const DEFAULTTHEME = 'isleen';

**Comment by micagroup** [comment]
I'm sorry, but I don't know how that works. I would love to give you some usefull feedback, but with these instructions I'm getting nowhere.

![image](https://cloud.githubusercontent.com/assets/4655615/8854559/bfd569ec-3160-11e5-9cd6-56c28342ece3.png)

![image](https://cloud.githubusercontent.com/assets/4655615/8854588/de41209c-3160-11e5-86ff-037e3e94400f.png)

Error when trying to load widget;
![image](https://cloud.githubusercontent.com/assets/4655615/8854611/ff0c81a4-3160-11e5-8eec-e7b76966c7c0.png)

**Comment by mustafhae** [comment]
committed notification disabled

**Comment by mustafhae** [comment]
did your issue fixed

**Comment by agilisgmbh** [comment]
I also got the same problem as micagroup.
You told us we should disable notifications, but no one knows HOW!
ALso you dont answer via E-Mail - so i´ll try here to:

SAME Errors as @micagroup 
1. Access Denied
2. tpl missing (when have alook at vtigers vlayout, there seems to be missing more then 10 tpls
3. Widget on dashboard error.

So - please provide UNDERSTANDABLE Support - or dont offer it...
thanks (sry, but waiting for 5! days for an answer, yet)

**Comment by mustafhae** [comment]
Hi 

We committed disabled notification code.

thank

**Comment by mustafhae** [comment]
Added installation instruction in readme file

**Comment by agilisgmbh** [comment]
Sorry, but you DID NOT give instructiuons in readme about how to disabling notifications...
