### ISSUE TITLE
Not working fine with v6.3

### ISSUE THREAD

**Issue by agilisgmbh** [isleensolutions/vtigerTemplate#2]
There are many Bugs, e.g. at Dashboard (errors with counter), Dashboard Widgets, missing (think 10!) .tpl files (always errors), and few other things.
When do you plan to fix this?

**Comment by mustafhae** [comment]
which version of vtiger you are using

**Comment by agilisgmbh** [comment]
You can see on the TOPIC TITLE:
"Not working fine with v6.3"

**Comment by mustafhae** [comment]
It wouldn't work with 6.3, There are many tpl files are added for vt6.3 and template work for vt6.0.0 we mentioned in readme file

**Comment by agilisgmbh** [comment]
Guys! 6.0 is buggy, crappy and outdated!
6.0 -> 6.1 -> 6.2 -> 6.3
6.0 installed is a security problem, too.
So DO you plan to update for the ACTUAL STABLE or not?

**Comment by mustafhae** [comment]
yes.. we will release for all version soon...
